{% set version = "1.1.1" %}

package:
  name: vega
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/v/vega/vega-{{ version }}.tar.gz
  sha256: c6a9b84cd2b1a6771c71cb86bb7ac7fbb4128e001e478b1c702542b1121359eb

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - jupyter
    - pandas

test:
  imports:
    - vega

about:
  home: https://github.com/vega/ipyvega
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'An IPython/Jupyter widget for Vega and Vega-Lite'

extra:
  recipe-maintainers:
    - jakevdp
    - ellisonbg
    - domoritz
    - ocefpaf
