{% set version = "3.1.0" %}

package:
  name: vega
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/v/vega/vega-{{ version }}.tar.gz
  sha256: 2e80a000c35e8c28f3853344f11129d55fc1316e8bd966af363533ec8fd174a0

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - poetry >=0.12
  run:
    - python
    - jupyter >=1.0.0,<2.0.0
    - pandas >=0.25.3,<0.26.0

test:
  imports:
    - vega

about:
  home: https://github.com/vega/ipyvega
  license: BSD-3-Clause
  license_file: LICENSE
  summary: An IPython/Jupyter widget for Vega and Vega-Lite

extra:
  recipe-maintainers:
    - jakevdp
    - ellisonbg
    - domoritz
    - ocefpaf
