{% set version = "2.6.0" %}

package:
  name: vega
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/v/vega/vega-{{ version }}.tar.gz
  sha256: c66354d6d164cc3d7254bcd129d8d861daf4a9e9cb8738b1724791777f6c29f0

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - jupyter
    - pandas

test:
  imports:
    - vega

about:
  home: https://github.com/vega/ipyvega
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'An IPython/Jupyter widget for Vega and Vega-Lite'

extra:
  recipe-maintainers:
    - jakevdp
    - ellisonbg
    - domoritz
    - ocefpaf
