{% set version = "2.1.0" %}

package:
  name: vega
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/v/vega/vega-{{ version }}.tar.gz
  sha256: abb93e4af0f97b4ca7a5034bc1c358b9863ece536b4b9c9707551011b7e65053

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - jupyter
    - pandas

test:
  imports:
    - vega

about:
  home: https://github.com/vega/ipyvega
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'An IPython/Jupyter widget for Vega and Vega-Lite'

extra:
  recipe-maintainers:
    - jakevdp
    - ellisonbg
    - domoritz
    - ocefpaf
