# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "JSZOnpPaS6GDRNQB6PzLurqVqKtTxsYA5MDJy7zphK6jgKCijKtNwnzpMoGtSNiETnzMiTNmheGrMhwAcyfkv2q37q0dQ6iZwmjIdYSyIOWeZv+6NkcLTJFbbZfm7ib7irKoYRkfZJ8m71SIXLJOGCx9MxS5lJ9WfF86A47xLd0judZpAQHqLRJWHQ3biQE+0bzTCMfTtlmNrz1B5vG/GNbdHoJIwRJ8YrBfAl9Ep6zR03poiBoG2ykp1vUOJ3owl4q/RunxMmCUSRp0Moqi+Zi+J9B2BYqRgsEcmcqDODiaNtaIIF6uz7UqzIZL6euC+kNqqVJeOk+lOphyE3m4105RXfvv3XNSMtbLAtdKOVHmoY+OscAtb7nYdABRDoyiEpQLNhBQKOIRQN1D4zaAV1GAGXvWeHFWqdZ++4YLeIbifAwkVJi/4bzDjdk1wG6kYhpX8g9xOlMUSRSyb/n1AhDRLoLBBLHO+nU7M7URocT16odEO4j69uMVUKBgODeS+x78peZtGNhAwnplNN+ayfX3+tajlV7/WsS7C1NAbyBiG7oEuhr7WQGiaM+0fg2iICLS8Yzx9yNtv05EHzgNu19K2dMGZErYDWI/SEajNiact43YnOmn1ZSc5T6dizPFUuGHmsxhT1GXIClokWoNr2zKAuFdFlNJyLR2uDsUWyI="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
