travis:
  secure:
    BINSTAR_TOKEN: apvTKuDwcYgoycBb60ki4BMmBq1YWn+HeKQvayJNnFwtAjC/yU9BO8umrUND2eVeW5fF9UxLz9PIZ4oZ9EzW+ab3ktZ1F35BCp8V0YV7V/T2ryJPHEC7MA/paec9M6lF2aP9HfYQ48VjoZc7G1iQicIve2fxqSjt07Y+bVqhx16iZafG7FPkSbuEl0tHGFDv+YJGzn5pCm1MxBK99QKPXXVqIs53A3LDL4oy4aOVvmbBHCnYxTMdqt+xpv/8OK/9Wb32Q91SjiVsdxTH0udu3joDwsplz4+bq164gQKjYc8KdJid0XHqiK8U0jCfbLyhPPyf7KsXHaVavbd1MnL3Mfd5IwDZmb9wag5yWKV1zGQNoarFJsSXIVYPFJXzH8i+l1aLBcRjZf6FmPOUxidc2YQM/Rzi94fIqU27jikb7jrHeOBFinaFlIgwo3KTdE0uhirV2PKxNU0hxTat9jBKRE2fixLtARCOPFzqWTAtagmKPuSIGvunK3R8SObEKTxEG4fZbaHSdWGn2OXD9czvKkJwSJb2+Hhq6GRYdFjAqtplp+dHPklSnlv2bhtASD1ubUxcHzDT5yHqIeWeFf7QPIxF8Bkdhi3hXrNti9C1ZWj7hQAPeGc20R/oRdHNBD8b0cCb1Hl2+8+I/0uaPNg8GYYXJgd8WrgyPrbvyWHKFGM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
